Decorate a class
henrycode460/OOP_School_Library pull request #2
Opened 2022-09-07 15:48 UTC by henrycode460

This branch contains the followings:

- A ``Nameable``, ``BaseDecorator``, ``CapitalizeDecorator``, and ``TrimmerDecorator`` class
- The ``Person`` inherit the ``Nameable`` class
- The ``CapitalizeDecorator``, and ``TrimmerDecorator`` inherit ``BaseDecorator`` class
- Value from the ``class_name`` method in the  ``CapitalizeDecorator`` output in ``uppercase``
- Value from the ``class_name`` method in the  ``TrimmerDecorator`` output is trimmed to a maximum length of  ``10``

2022-09-07 17:32 UTC, Ismailco requested changes
### Hi @henrycode460, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 17:32 UTC, Ismailco commented on baseDecorator.rb
> +  end
- [ ] This method should return @nameable.correct_name, not put the nameable, kindly fix this so it returns the correct value

2022-09-07 17:32 UTC, Ismailco commented on person.rb
> +  end
- [ ] The method should return the @name, not print it to the console, kindly make the changes so the method return the @name

2022-09-07 17:32 UTC, Ismailco commented on capitalizeDecorator.rb
> +  end
- [ ] This method should capitalize only the first letter of the given name not the whole name, kindly consider fixing this so it returns the correct value

2022-09-07 19:07 UTC, Nemwel-Boniface requested changes
## Hello @henrycode460            :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] Kindly have a look into why the console throws an error when I run the tests. The test data I was using I placed it inside the Person.rb file is the following:

```
person = Person.new(22, 'maximilianus')
puts person.correct_name
capitalizedPerson = CapitalizeDecorator.new(person)
puts capitalizedPerson.correct_name
capitalizedTrimmedPerson = TrimmerDecorator.new(capitalizedPerson)
puts capitalizedTrimmedPerson.correct_name
```

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 19:07 UTC, Nemwel-Boniface commented on person.rb
> +require_relative 'nameable'
- [ ] Trying out your project locally, I got the error saying that the ```correct_name``` method was undefined. On further inspection, I realized that you had not included the following:

![image](https://user-images.githubusercontent.com/86318284/188956797-1ced5081-de6b-48f1-9383-e1f11a3ce4b9.png)


```
require_relative './baseDecorator'
require_relative './capitalizeDecorator'
require_relative './trimmerDecorator'
```

Despite making this change, I was still not able to run the console and test it correctly. Kindly have a look into why this is the case

2022-09-08 09:07 UTC, Rustamxon7 approved these changes
## Hello @henrycode460 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-08 09:08 UTC, merged